### ISSUE TITLE
pipeline doesn't run properly on my data

### ISSUE THREAD

**Issue by mars188** [HCGB-IGTP/XICRA#7] opened 2021-09-15 09:29 UTC
Hello, 

I created the conda environment and installed the XICRA and all its dependencies. When I run XICRA with the provided example data, it runs fine but when I try with my own data, it doesn't produce any input. For example, under the count folder it has *.tsv file but its empty. Also, it produces an empty "report" folder. So, I am wondering what could go wrong with my own data. 

I read  in the XICRA paper that "User must provide specific adapter sequences for the trimming analysis" whereas I don't know where to provide adapter sequences since XICRA contains only three steps i.e. 
1. prep
2. join
3. miRNA
Where am I supposed to provide adapter sequences?  

Here is the error that is produced when I run "miRNA" module using my own data. 

`Traceback (most recent call last):
  File "/scratch/gencore/conda3/envs/XICRA/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/gencore/conda3/envs/XICRA/bin/XICRA", line 305, in <module>
    args.func(args)
  File "/scratch/gencore/conda3/envs/XICRA/lib/python3.6/site-packages/XICRA/modules/miRNA.py", line 243, in run_miRNA
    generate_DE.generate_DE(results_df, options.debug, expression_folder)
  File "/scratch/gencore/conda3/envs/XICRA/lib/python3.6/site-packages/XICRA/scripts/generate_DE.py", line 50, in generate_DE
    all_data_filtered, all_data_duplicated = discard_UID_duplicated(all_data)
  File "/scratch/gencore/conda3/envs/XICRA/lib/python3.6/site-packages/XICRA/scripts/generate_DE.py", line 68, in discard_UID_duplicated
    new_data['miRNA']  = tmp[0]
  File "/scratch/gencore/conda3/envs/XICRA/lib/python3.6/site-packages/pandas/core/frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/scratch/gencore/conda3/envs/XICRA/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 0
`
Please let me know if I am missing something. Many thanks in advance!

**Comment by mars188** [comment] 2021-09-15 09:36
Here is my script for the run:

`XICRA miRNA --input data_analysis --software miraligner`

BTW, the preceding two steps (prep and join) seemed to work fine since I obtained the *joined.fastq files with good size.

**Comment by JFsanchezherrero** [comment] 2021-09-15 09:52
Hello there,

Thank you very much for using XICRA.

I can see in your first message that you are missing the `trimm` module where you provide the sequence adapters. The message you state is a consequence of missing mapping data due to adapters in the sequence.

I also assume it is paired end data that is why you use `join` module.

Basically, the main and necessary steps for XICRA analysis are: 

```
## paired-end XICRA analysis
XICRA prep --input raw_data_fastq_files --output XICRA_analysis

## quality control
XICRA QC --input XICRA_analysis/ 

## trimm adapters
XICRA trimm --input XICRA_analysis --adapters_a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC --adapters_A GATCGTCGGACTGTAGAACTCTGAACGTGTAGATCTCGGTGGTCGCCGTATCATT --threads 4

## join
XICRA join --input XICRA_analysis/ --perc_diff 0 --threads 24

## miRNA
XICRA miRNA  --software miraligner --input XICRA_analysis/
```

I encourage you to re-run the full analysis from scratch either removing the previous folder or using a different name.

**ATTENTION**, take into account that the sequence adapters provided here are just an example. **PLEASE** provide your specific adapter sequence for your smRNA library setup.

Please contact me for further details or keep me updated if you manage to sort out the problem and successfully run XICRA.

Best regards,
Jose F.

**Comment by mars188** [comment] 2021-09-16 06:07
Dear Jose, 

Thank you for the quick response. I followed all your direction but still get the same error. Here is the detail of steps I perfromed.

1.  `XICRA prep --input test_raw_files --output test_analysis` and this seemed to have worked.
2. `XICRA QC --input test_analysis/ ` 
3. `XICRA trimm --input test_analysis --adapters_a TGGAATTCTCGGGTGCCAAGG --adapters_A TGGAATTCTCGGGTGCCAAGG --threads 24` here I used the same adapter sequences for a and A. This step seemed to go well. 
4. `XICRA join --input test_analysis/ --threads 24` this step seemed to go well too. 
5. `XICRA miRNA  --software miraligner --input test_analysis/` however this step produced the following error:

`+ miRNA analysis is finished...
+ Let's summarize all results...
Successfully created the directory /scratch/gencore/ma5877/small_RNA/paired_end/test_analysis/report/miRNA
+ Summarize miRNA analysis for all samples...

+ Summarizing results for software:  miraligner
+ Reading information from sample:  100_S54
         - Information not available for sample:  100_S54
+ Reading information from sample:  103_S44
         - Information not available for sample:  103_S44
+ Reading information from sample:  106_S60
         - Information not available for sample:  106_S60
Traceback (most recent call last):
  File "/scratch/gencore/conda3/envs/XICRA/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/gencore/conda3/envs/XICRA/bin/XICRA", line 305, in <module>
    args.func(args)
  File "/scratch/gencore/conda3/envs/XICRA/lib/python3.6/site-packages/XICRA/modules/miRNA.py", line 243, in run_miRNA
    generate_DE.generate_DE(results_df, options.debug, expression_folder)
  File "/scratch/gencore/conda3/envs/XICRA/lib/python3.6/site-packages/XICRA/scripts/generate_DE.py", line 50, in generate_DE
    all_data_filtered, all_data_duplicated = discard_UID_duplicated(all_data)
  File "/scratch/gencore/conda3/envs/XICRA/lib/python3.6/site-packages/XICRA/scripts/generate_DE.py", line 68, in discard_UID_duplicated
    new_data['miRNA']  = tmp[0]
  File "/scratch/gencore/conda3/envs/XICRA/lib/python3.6/site-packages/pandas/core/frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/scratch/gencore/conda3/envs/XICRA/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 0`

I would appreciate if you could help me to point out where it goes wrong. Many thanks!

**Comment by mars188** [comment] 2021-09-16 06:38
Yes, it's paired-end reads.

**Comment by JFsanchezherrero** [comment] 2021-09-16 06:57
Hi there, 

Thank you very much for the details. I guess the problem is that there is no data available for any sample in the miRNA final step.

Let me tell you a couple of things to check:

- Check MultiQC reports in `test_analysis/report` folder either for raw fastq reads and trimmed fastq reads. Check if there is anything unusual and read length matches your expected library size.

- On the other hand, check `cutadapt` options in order to correctly include adapters. 
https://cutadapt.readthedocs.io/en/stable/guide.html
https://cutadapt.readthedocs.io/en/stable/guide.html#trimming-paired-end-reads

Basically, XICRA calls `cutadapt` and provides options provided to `XICRA trimm` module such as `-a adapter1` and `-A adapter2`. Please note there is an additional option within `XICRA trimm` (`--extra`) to provide any additional parameters to pass to `cutadapt`.

You mentioned that process finished correctly. It did finish but I am not sure if reads are correctly trimmed. I don't think you should be using same adapters for both ends.  That might cause to avoid mapping in following miRNA module. 

- You can also check for each sample, within the miRNA folders, if there is any file generated containing information.

- Additionally, if RAM is not issue for you (>32Gb) you might check the small RNA biotypes available for each sample. It would create a `STAR` mapping (it demands many RAM) and then assign feature for each biotype. You should be able to see that most of your reads as classified as miRNA, if not, something might happened during library processing.

Please let me know how you proceed and if you succeeded.

**Comment by mars188** [comment] 2021-09-22 06:34
Thank you so much. Now it works. The problem was that I was using the same adapter for the a and A. I found out the second adapter and it just worked.

**Comment by hcgb-admin** [comment] 2021-09-23 08:45
Hi there,

Great! I am glad you get to run XICRA on your paired-end read small RNA seq data.

Once you have generated the miRNA counts table, you can use the `XICRA.stats` R package to handle data either at isomiR, miRNA or type of variation.

I would close this issue so far as it is solved. Do not doubt to contact us for any further information or if you need more guidance, please open it again or a new one.

Best regards,

**Closed by hcgb-admin** 2021-09-23 08:45 UTC
